homeassistant:
  name: Test Home
  latitude: 32.87336
  longitude: -117.22743
  elevation: 430
  unit_system: metric

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
